[build-system]
requires = ["setuptools>=42", "wheel", "pybind11~=2.12.0"]
build-backend = "setuptools.build_meta"

[project]
name = "eccn"
version = "0.1"
description = "Clear description"
authors = [{name = "Author", email = "author@email.com"}]
# license = {file = "LICENSE.txt"}
requires-python = ">=3.9"
readme = "README.md"
dependencies = [
    "loky>=3.4.1",
    "numpy>=1.23",
    "scikit-learn"
]
